apiVersion: v1
kind: Service
metadata:
  name: food-app-service
spec:
  selector:
    app: food-app-v3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort # Use 'NodePort' or 'ClusterIP' if not using a cloud provider
